<a href="https://colab.research.google.com/github/satwika-mand/DL_img_fusion1/blob/main/ml_course_work_6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from sklearn.datasets import load_iris
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn import metrics
import numpy as np

In [3]:
dataset=load_iris()
X_train,X_test,y_train,y_test=train_test_split(dataset["data"],dataset["target"],random_state=0)

In [4]:
kn=KNeighborsClassifier(n_neighbors=1)
kn.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=1)

In [6]:
for i in range(len(X_test)):
  x=X_test[i]
  x_new=np.array([x])
  prediction=kn.predict(x_new)
  print("Target=",y_test[i],dataset["target_names"][y_test[i]],"PREDICTED=",prediction,dataset["target_names"][prediction])
  print(kn.score(X_test,y_test))

Target= 2 virginica PREDICTED= [2] ['virginica']
0.9736842105263158
Target= 1 versicolor PREDICTED= [1] ['versicolor']
0.9736842105263158
Target= 0 setosa PREDICTED= [0] ['setosa']
0.9736842105263158
Target= 2 virginica PREDICTED= [2] ['virginica']
0.9736842105263158
Target= 0 setosa PREDICTED= [0] ['setosa']
0.9736842105263158
Target= 2 virginica PREDICTED= [2] ['virginica']
0.9736842105263158
Target= 0 setosa PREDICTED= [0] ['setosa']
0.9736842105263158
Target= 1 versicolor PREDICTED= [1] ['versicolor']
0.9736842105263158
Target= 1 versicolor PREDICTED= [1] ['versicolor']
0.9736842105263158
Target= 1 versicolor PREDICTED= [1] ['versicolor']
0.9736842105263158
Target= 2 virginica PREDICTED= [2] ['virginica']
0.9736842105263158
Target= 1 versicolor PREDICTED= [1] ['versicolor']
0.9736842105263158
Target= 1 versicolor PREDICTED= [1] ['versicolor']
0.9736842105263158
Target= 1 versicolor PREDICTED= [1] ['versicolor']
0.9736842105263158
Target= 1 versicolor PREDICTED= [1] ['versicolor']
0

In [8]:
from sklearn.metrics import confusion_matrix
y_pred=kn.predict(X_test)
cm=confusion_matrix(y_test,y_pred)
print(cm)

[[13  0  0]
 [ 0 15  1]
 [ 0  0  9]]


In [9]:
from sklearn.metrics import accuracy_score
accuracy=accuracy_score(y_test,y_pred)
print(accuracy)

0.9736842105263158


In [10]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        13
           1       1.00      0.94      0.97        16
           2       0.90      1.00      0.95         9

    accuracy                           0.97        38
   macro avg       0.97      0.98      0.97        38
weighted avg       0.98      0.97      0.97        38



In [12]:
from sklearn.metrics import mean_squared_error
mean=mean_squared_error(y_test, y_pred)
print("mean_squared_error",mean)


mean_squared_error 0.02631578947368421


In [14]:
from sklearn.metrics import r2_score
r2_score=r2_score(y_test, y_pred)
print("r2_score ", r2_score)


r2_score  0.9536585365853658
r2_score  0.9536585365853658


In [15]:
from sklearn.metrics import adjusted_rand_score
adjusted_rand_score=adjusted_rand_score(y_test, y_pred)
print("Adjusted Rand Score: ", adjusted_rand_score)

Adjusted Rand Score:  0.9226346053319394


In [16]:
kn=KNeighborsClassifier(n_neighbors=5)
kn.fit(X_train,y_train)

KNeighborsClassifier()

In [17]:
for i in range(len(X_test)):
  x=X_test[i]
  x_new=np.array([x])
  prediction=kn.predict(x_new)
  print("Target=",y_test[i],dataset["target_names"][y_test[i]],"PREDICTED=",prediction,dataset["target_names"][prediction])
  print(kn.score(X_test,y_test))

Target= 2 virginica PREDICTED= [2] ['virginica']
0.9736842105263158
Target= 1 versicolor PREDICTED= [1] ['versicolor']
0.9736842105263158
Target= 0 setosa PREDICTED= [0] ['setosa']
0.9736842105263158
Target= 2 virginica PREDICTED= [2] ['virginica']
0.9736842105263158
Target= 0 setosa PREDICTED= [0] ['setosa']
0.9736842105263158
Target= 2 virginica PREDICTED= [2] ['virginica']
0.9736842105263158
Target= 0 setosa PREDICTED= [0] ['setosa']
0.9736842105263158
Target= 1 versicolor PREDICTED= [1] ['versicolor']
0.9736842105263158
Target= 1 versicolor PREDICTED= [1] ['versicolor']
0.9736842105263158
Target= 1 versicolor PREDICTED= [1] ['versicolor']
0.9736842105263158
Target= 2 virginica PREDICTED= [2] ['virginica']
0.9736842105263158
Target= 1 versicolor PREDICTED= [1] ['versicolor']
0.9736842105263158
Target= 1 versicolor PREDICTED= [1] ['versicolor']
0.9736842105263158
Target= 1 versicolor PREDICTED= [1] ['versicolor']
0.9736842105263158
Target= 1 versicolor PREDICTED= [1] ['versicolor']
0

In [18]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        13
           1       1.00      0.94      0.97        16
           2       0.90      1.00      0.95         9

    accuracy                           0.97        38
   macro avg       0.97      0.98      0.97        38
weighted avg       0.98      0.97      0.97        38

